# Generated by Django 4.2.5 on 2023-12-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0004_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='ingresos_arriendo',
            field=models.IntegerField(default=0),
        ),
    ]
