# Generated by Django 4.2.5 on 2023-12-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0005_alter_tienda_ingresos_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('costo_reparacion', models.IntegerField(default=0)),
            ],
        ),
    ]
